version: "3.9"

services:
  postgres-task:
    image: postgres:16
    container_name: postgres-task
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - task-postgres-data:/var/lib/postgresql/data
    networks:
      - tasknet

  postgres-user:
    image: postgres:16
    container_name: postgres-user
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - tasknet

  task-service:
    build:
      context: ./tasksvc
      dockerfile: Dockerfile
    container_name: task-service
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres-task:5432/taskdb?sslmode=disable
      USER_SERVICE_URL: http://user-service:8081
    depends_on:
      - postgres-task
      - user-service
    ports:
      - "8080:8080"
    networks:
      - tasknet

  user-service:
    build:
      context: ./usersvc
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres-user:5432/userdb?sslmode=disable
    depends_on:
      - postgres-user
    ports:
      - "8081:8081"
    networks:
      - tasknet

volumes:
  task-postgres-data:
  user-postgres-data:

networks:
  tasknet:
    driver: bridge
